### PR TITLE
Add steps to install from source

### PR DESCRIPTION
**Pull request by paniabhisek**
Installing from pypi is not recommended as mentioned by jeremy(due to it's rapid changes) and you don't want to use conda on Google Colab.

So Add steps to install from source

### CODE REVIEW

**Comment by ELC** [comment]
I believe that instead of using `git clone https://github.com/fastai/fastai.git`, it should be used something like this:

```
# Clone the repo for locally build or update the repo if already exists
!bash -c '[ -d fastai ] && cd fastai && git pull'
!bash -c '! [ -d fastai ] && git clone https://github.com/fastai/fastai.git'
```
This way, if the folder already exists, it doesn't throw an error and it updates the repo, if not, it clones the repo. I admit it isn't the most elegant solution but there might be other way to achieve this.

Another way is to use the `%%bash` magic:

```
%%bash

# Clone the repo for locally build or update the repo if already exists

if [ -d fastai ]
then
  cd fastai
  git pull
else
  git clone https://github.com/fastai/fastai.git
fi
```

**Comment by ELC** [comment]
Although this might be an overkill, the process of building and installing fastai could avoid any hard coded string with the following code:

```
# Clean the dist folder
!rm -rf fastai/dist

# Create a Tarball using sdist
!cd fastai && python setup.py sdist

# Install through pip
!cd fastai/dist && pip install $(ls)
```

It could be split in 3 cells with the `!` or it could also be in one cell and with the %%bash magic to avoid the `!`, in this case it could be combine with the previous comment in and create a single cell with the `%%bash` magic for succinctly

The last line could be replace with `!pip install fastai/dist/$(ls fastai/dist/)` but it seems much more confusing to me.

**Comment by paniabhisek** [comment]
@ELC Thanks for your input.

I'll add all of them in one single cell as someone might just want to run one single cell to install fastai. It'll be:

```
%%bash

# Clone the repo for locally build or update the repo if already exists

if [ -d fastai ]
then
  cd fastai
  git pull
else
  git clone https://github.com/fastai/fastai.git
  cd fastai
fi

# Clean the dist folder
rm -rf dist

# Create a Tarball using sdist
python setup.py sdist

# Install through pip
pip install dist/$(ls dist)
```

Give your suggestion if something needs to be changed.

**Comment by ELC** [comment]
I tried several alternatives, the one you proposed usually throw me a error/warning that make me think something is wrong. I found out that the most legible and simple way is the following:

```
%%bash

if ! [ -d fastai ]
then
  git clone https://github.com/fastai/fastai.git
fi

cd fastai

git pull

pip3 -q install . && echo Successfully Installed Fastai
```

Do you see any potential disadvantages of using pip directly instead of generating a source distribution with sdist?

Another option is to combine both fasai and pytorch installation in a single cell like this:

```
%%bash

if ! [ -d fastai ]
then
  git clone https://github.com/fastai/fastai.git
fi

cd fastai

git pull

pip3 -q install .  && echo Successfully Installed Fastai

pip3 -q install http://download.pytorch.org/whl/cu91/torch-0.3.1-cp36-cp36m-linux_x86_64.whl && echo Successfully Installed PyTorch

pip3 -q install torchvision && echo Successfully Installed TorchVision
```

Note that this pytorch version is the one I submitted in a PR, it's not the same as masters

Colab doesn't discriminate between python3 and python, neither between pip and pip3. However, since we are in a linux architecture I think we should keep the convention of naming python3 and pip3 for compatibility reasons, specially if someone downloads the notebook and uses it locally

**Comment by paniabhisek** [comment]
I didn't get any warning/error when I ran that cell. Even after couple of times, no error/warning
But I still like the idea of merging

```
# Create a Tarball using sdist
python setup.py sdist

# Install through pip
pip install dist/$(ls dist)
```

into

```
pip -q install .
```

I could've thought of that in the first place, that's dumb!

I don't want to add `pytorch` in this cell as that is already in `requirements.txt`. If the `requirements.txt` changes with different version of `pytorch`, this might fail

The idea of using `pip` is that, it can be run in both `python2` and `python3`. In both `colab` and local `jupyter-notebook` we can change runtype as `python2`/`python3`. So I believe using `pip` is a good idea in this case.

**Comment by ELC** [comment]
Great then! 

I mentioned the manual install of Pytorch in order to select the specific version of CUDA but if that doesn't implies any disadvantages, I believe it's fine.

I added the `&& echo ...` because the solution uses the `-q` option. Of course they are completely optional, I just want to have a clear yet short answer for each command.

I also agree with you regarding the use of pip over pip3, personally I use pipenv on a daily basis and pip is preferred over pip3 since most of the time I work in virtual environments.

**Comment by paniabhisek** [comment]
@ELC 

My bad about the warning, I was looking for red highlighted text in colab. Turns out github only highlights in red not colab.

I've added you as author of commit as well.

@corykendrick let us know whether this PR is fine ?

**Comment by ELC** [comment]
Now that you've made all the modifications I believe you should remove the cells where fastai is installed via pip (legacy) and move the new section (Installing fastai from source) just above (Special additions for particular lessons). Currently there are two places where fastai is installed and that's not ideal.

I prepared [a gist](https://gist.github.com/ELC/756040fe84a8bb3d14c59b0e997c84e9) where you can see how I structure the notebook. The gist was meant for working and not necessarilly to follow the course, but my approach was the following, for each lesson, download the notebook and copy paste the cells of the gist at the top and then you have a complete lesson in Colab. (The sections regarding downloading the data files should be added in other to test the lesson code though.)

**Comment by paniabhisek** [comment]
I like to open course notebook in one window and `fastai_in_colab` in another. Than install fastai and download datas in `fastai_in_colab` notebook and then head over to course notebook which is opened in another window. In this way I avoid copying to each of the course notebooks.

If the structuring of the notebook can be improved, then you should create a new PR.

In the original notebook there are some places where `pip` is used and some places where `pip3` is used. For that also I think we should create a new PR.

Anyway I've changed according to your suggestion, review it.

**Comment by ELC** [comment]
I believe that the notebook is ready, no more suggestions for now.

Following your method, could you run the cells in the course notebook without adding the installing cells for fastai? How do you "share" the installation across notebooks?

I created that gist to have a personal derivate that would work both for the course and general purpose. I just wanted something I could hit "Run All" and wait and when it ends, I'm ready to go. That was my objective, I saw this repo and use it as a template.

**Comment by paniabhisek** [comment]
You need the installing cells for `fastai`. You just don't need to copy them to other notebooks.
When you run a cell in `colab`, the run type is available across all notebooks for that gmail user. So you just need to install `fastai` in one notebook and `fastai` is available throughout all other notebooks.

**Comment by ELC** [comment]
I didn't know that! That's awesome and a great insight! Is it in some part of the docs where I can refer to?

I tested the notebooks this morning and the code is broken, FastAI has released the 1.0.3 version and the code no longer works, it throws `ModuleNotFoundError`. I wouldn't be able to test and fix until 2 or 3 days.

**Comment by paniabhisek** [comment]
`pytorch 1.0rc1 and 1.0rc0` has been released hours ago. So `fastai` is moving to support early alpha version of `pytorch`. The code has been changed substantially I guess and all codes in 0.7 has been moved to `old` folder inside `fastai`(no idea why they are putting in `old` folder, they could've removed it completely).

So the imports such as

```
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *
```
 are not working now. But `from fastai.imports import *` still works.

So I'll port back the cell where we had installing from `pypi` and Add this section after that. Also I can add comment where it warns about this issue. When they release new course supporting alpha version, we can remove the section which uses `pypi`.

But I don't see where they released 1.0.3 ?

Tell me if there is any better way

> I didn't know that! That's awesome and a great insight! Is it in some part of the docs where I can refer to?

I was playing around to find a easier way. Don't know if there is any docs.

**Comment by ELC** [comment]
The release isn't in the releases tab but in https://github.com/fastai/fastai/commit/614f25a00fa6aa7de4e0dbdda393d25f63aa23ed. Also in the readme there are recommendations to manually install pytorch and torchvision.

Upload the changes you consider necessary, I will check them as soon as I'm free

**Comment by ELC** [comment]
I made some tests and this seems to work:

```
!pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html
!pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ torchvision==0.2.1.post1
!pip install fastai
```

Also, there is no place in the docs about how the imports should be made now, they implemented an `imports` folder with a `__init__.py` file instead of a `imports.py`, I think that's why the other imports were broken.

Running the above code plus `from fastai.imports import *` seems to work without any problems.

UPDATE 04.10.2018

It is now possible to install FastAI 0.7 without any problems with the following code

```
%%bash

if ! [ -d fastai ]
then
  git clone https://github.com/fastai/fastai.git
fi

cd fastai

git pull

cd old

pip -q install .  && echo Successfully Installed Fastai 0.7

pip -q install http://download.pytorch.org/whl/cu91/torch-0.3.1-cp36-cp36m-linux_x86_64.whl && echo Successfully Installed PyTorch

pip -q install torchvision && echo Successfully Installed TorchVision
```

Both GPU `CUDA` and `cuDNN` are `True`


I have both approaches in this [gist](https://gist.github.com/ELC/756040fe84a8bb3d14c59b0e997c84e9)

**Comment by paniabhisek** [comment]
Hey you're back early!!

Check [this](https://github.com/fastai/fastai/blob/master/setup.py#L36). This will be removed soon I guess, so quoting:

> XXX: require torch>=1.0.0 once it's released, for now get the user to install it explicitly

We can not add cell to install from source even if `torch>=1.0.0` is released. Because the current course can not be followed with the latest source because of [this](https://github.com/fastai/fastai#note-for-coursefastai-students), which says:

> If you are using fastai for any [course.fast.ai](course.fast.ai) course, please do NOT install fastai from pip or conda using the instructions below; the instructions below are for fastai v1, but the courses use fastai 0.7. For the courses, you should simply follow the instructions in the course (i.e. clone this repo, cd to it, and `conda env update`), and the notebooks will work (there is a symlink to old/fastai/, which is fastai 0.7, in each course notebook directory), or else use `pip install fastai==0.7.0` to install the version compatible with the course.

> Note: *If you want to learn how to use fastai v1 from its lead developer, Jeremy Howard, he will be teaching it in the [Deep Learning Part I](https://www.usfca.edu/data-institute/certificates/deep-learning-part-one) course at the University of San Francisco from Oct 22nd, 2018.*

It recommends to install `fastai` using `pip install fastai==0.7.0`. But I believe the `old` folder is little ahead of `0.7.0`

So what's your take ? Should I close this pull request(When the course for `Oct-2018` course will be available, I'll open it again to install from source) or add instructions to install from `old` folder.

**Comment by paniabhisek** [comment]
Well the original `fastai_in_colab` repo is broken anyway. As the latest version for `fastai` is `1.0.4`

**Comment by ELC** [comment]
I believe that there are two main intentions with this repo:

- Provide an easy setup for fastai to follow the course
- Provide an easy setup for fastai for general purpose

For the first, the 0.7 version is needed (at least the new version of the courses are released) and for the second it might also be needed to use the 0.7 until the docs and the course are available in order to notice the difference between 0.7 and 1.x

Installing fastai v1 just require two steps instead of three

> Follow the following 2 steps in this exact order:
> 
> Install the nightly pytorch build, with cudaXX package version matching your system's setup. For example for CUDA 9.2:
> 
> `pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html`
> 
> Install fastai:
> 
> `pip install fastai`
>
> NB: this will also fetch torchvision-nightly, see the conda entry above for details.

And installing fastai v0.7 just requires one step as you previously said `pip install fastai==0.7.0` although they made 0.7.1 and 0.7.2 releases in the past 12 hours, but they point the same commit, maybe a confusion? I don't really understand why they did so.

I don't know the author's intentions but I believe we should keep it updated with both version as the gist I mentioned earlier.

What's your opinion?

**Comment by Abhisek-** [comment]
Well the description of this repo indicates only for fastai course. But I like the idea of yours.

I can add two different sections: one for course and one for general purpose. Later, once the new course is live I can change that.

**Comment by paniabhisek** [comment]
Well the description of this repo indicates only for fastai course. And the major part of the notebook is about how to download datas for specific lessons of the course.

I'll open it again, when the new course will be available

**Pull request closed without merging**
